import pandas as pd
import matplotlib.pyplot as plt

try:
    # Read the CSV file generated by the C program
    df = pd.read_csv('distribution.csv')

    # Plotting
    plt.figure(figsize=(12, 7))
    
    # Plot a line for each state
    for col in df.columns:
        if col != 'n':
            plt.plot(df['n'], df[col], label=col, marker='.', markersize=5)

    plt.title('Evolution of State Distribution \u03A0(n)')
    plt.xlabel('Step (n)')
    plt.ylabel('Probability')
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.grid(True, which='both', linestyle='--', linewidth=0.5)
    plt.tight_layout()
    
    print("Displaying plot...")
    plt.show()

except FileNotFoundError:
    print("Error: 'distribution.csv' not found. Please run the C program first.")
except Exception as e:
    print(f"An error occurred: {e}")